In [1]:
import torch
import numpy

## Best way to create X_before_pooling?

In [14]:
X_before_pooling = torch.tensor([])
print('X before pooling before appending: {}'.format(X_before_pooling))

a = torch.randn(5, 5)
b = torch.randn(5, 5)
print(a, b)

print(X_before_pooling)

X before pooling before appending: tensor([])
tensor([[-1.6920, -0.8894, -0.8353, -0.9314, -0.2614],
        [ 1.4689,  1.4129,  0.8143,  0.6810,  0.7611],
        [ 0.4124,  1.2164, -0.6203, -1.6592,  0.6160],
        [-0.0352, -1.2103,  0.5547,  1.2982, -1.1753],
        [-1.1694, -0.1647, -1.3840, -1.2145,  1.2190]]) tensor([[ 0.9956, -0.3950,  0.3607, -0.0694,  1.7188],
        [-0.1851, -1.6884, -2.1094,  0.0044, -2.1059],
        [ 1.7329,  0.8434,  1.1377, -0.6874, -0.6998],
        [ 0.3192, -1.8128,  0.1668, -1.5976,  0.4167],
        [ 0.3233, -0.1409,  1.2316,  1.9350,  2.1961]])
tensor([])


In [29]:
# Pre-allocate bigger tensor and just fill it in
X_before_pooling = torch.Tensor(5, 5)
print(X_before_pooling)
a = torch.randn(5)
b = torch.randn(5)
print(a, b)
X_before_pooling[0,:] = a
X_before_pooling[1,:] = b
print(X_before_pooling)

tensor([[2.5226e-18, 2.4283e-18, 2.6302e+20, 6.1949e-04, 2.5640e-09],
        [1.0501e-05, 3.1129e+12, 2.7096e-09, 6.6395e-07, 6.4108e-10],
        [1.2893e+16, 1.2849e+31, 1.8395e+25, 6.1963e-04, 8.2731e+20],
        [1.7585e-04, 2.7056e+23, 2.1393e+23, 4.2317e+21, 5.4661e+22],
        [2.1476e-04, 1.7079e-07, 2.3049e-12, 7.1856e+22, 4.3605e+27]])
tensor([0.7856, 0.8672, 0.1497, 1.1798, 0.7877]) tensor([ 1.0430,  1.0147, -0.2423, -1.4829,  0.8172])
tensor([[ 7.8559e-01,  8.6724e-01,  1.4974e-01,  1.1798e+00,  7.8765e-01],
        [ 1.0430e+00,  1.0147e+00, -2.4225e-01, -1.4829e+00,  8.1721e-01],
        [ 1.2893e+16,  1.2849e+31,  1.8395e+25,  6.1963e-04,  8.2731e+20],
        [ 1.7585e-04,  2.7056e+23,  2.1393e+23,  4.2317e+21,  5.4661e+22],
        [ 2.1476e-04,  1.7079e-07,  2.3049e-12,  7.1856e+22,  4.3605e+27]])


## Initialize empty tensor

In [34]:
empty_tensor = torch.empty(2, 5)
print(empty_tensor)

tensor = torch.Tensor(2, 5)
print(tensor)

tensor([[1.6816e-44, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])
tensor([[ 0.0000e+00, -0.0000e+00, -4.2375e-38,  2.5250e-29,  9.8091e-45],
        [-0.0000e+00, -4.2374e-38, -3.6902e+19,  4.2039e-45,  0.0000e+00]])


## Iterating through bag

In [38]:
bag = torch.empty(3,5)
print(bag)

for i, instance in enumerate(bag):
    print('instance #{}: {}'.format(i, instance))

tensor([[ 0.0000e+00, -0.0000e+00, -3.4635e-38,  1.0845e-19,  1.1210e-44],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]])
instance #0: tensor([ 0.0000e+00, -0.0000e+00, -3.4635e-38,  1.0845e-19,  1.1210e-44])
instance #1: tensor([0., 0., 0., 0., 0.])
instance #2: tensor([0., 0., 0., 0., 0.])


## Aggregation

In [50]:
X_before_pooling = torch.randn(3,5)
print(X_before_pooling)

X_max, _ = torch.max(X_before_pooling, dim = 0)
print(X_max)

X_mean = torch.mean(X_before_pooling, dim = 0)
print(X_mean)

tensor([[-1.3571,  1.0196,  0.6668,  0.3015,  0.8708],
        [-1.7995, -0.4488, -0.3227, -0.2527,  0.2075],
        [ 0.2666,  0.4104, -0.7916,  0.2265, -0.5440]])
tensor([0.2666, 1.0196, 0.6668, 0.3015, 0.8708])
tensor([-0.9633,  0.3271, -0.1491,  0.0918,  0.1781])


## Matrix multiplication and transposing

In [53]:
X = torch.ones(3,5)
print(X)

weights = torch.ones(4, 5)*2
print(weights)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]])


In [55]:
X @ weights.t()

tensor([[10., 10., 10., 10.],
        [10., 10., 10., 10.],
        [10., 10., 10., 10.]])

## Adding bias

In [7]:
X = torch.randn(3, 5)
print(X)

bias = torch.randn(5)
print(bias)

print(X + bias)

tensor([[-0.9021,  0.1436,  2.4879, -0.6421, -2.1643],
        [-1.1591,  0.3825,  0.0510, -1.8364, -0.8634],
        [ 0.1113,  0.8304, -1.4286, -1.0422, -0.7285]])
tensor([-1.3368, -0.8511, -1.9846,  0.7704,  0.0288])
tensor([[-2.2389, -0.7075,  0.5033,  0.1283, -2.1355],
        [-2.4959, -0.4686, -1.9337, -1.0660, -0.8346],
        [-1.2255, -0.0207, -3.4132, -0.2718, -0.6997]])


## Indexing

In [8]:
array = torch.randn(10)
print(array)
print(array[:1])

tensor([ 0.8379, -1.0027, -0.1347, -0.9051,  0.2650, -1.3528,  0.2143,  0.4248,
        -0.0694, -1.2394])
tensor([0.8379])


## Filtering out invalid instances

In [11]:
X = torch.randn(10, 6)
X[:, 0] = 1
X[[1, 3, 5, 6 , 8], 0] = 0
print(X)

tensor([[ 1.0000, -2.2180, -0.4310,  0.1129,  0.1404, -2.9295],
        [ 0.0000,  1.1969,  0.4058, -1.5168,  1.2231,  0.3105],
        [ 1.0000,  0.8072,  0.5837,  2.2988, -0.3363, -1.9074],
        [ 0.0000,  1.7415, -0.3304,  1.3577,  0.3876, -1.0136],
        [ 1.0000,  0.0983,  1.2919, -1.1438,  1.4636, -0.0545],
        [ 0.0000, -0.4361, -0.3274,  0.2279,  0.0228,  1.1788],
        [ 0.0000,  0.2251, -1.1689, -1.2223, -0.2006,  0.6781],
        [ 1.0000,  0.9548,  0.1193, -0.5748,  0.0848, -0.4584],
        [ 0.0000, -0.9389, -0.2201,  0.1647, -0.9220, -0.5993],
        [ 1.0000,  0.2828, -0.5614, -0.7681,  1.2522,  0.1197]])


In [13]:
print(X[X[:,0] == 1, 1:])

tensor([[-2.2180, -0.4310,  0.1129,  0.1404, -2.9295],
        [ 0.8072,  0.5837,  2.2988, -0.3363, -1.9074],
        [ 0.0983,  1.2919, -1.1438,  1.4636, -0.0545],
        [ 0.9548,  0.1193, -0.5748,  0.0848, -0.4584],
        [ 0.2828, -0.5614, -0.7681,  1.2522,  0.1197]])


## 3D tensor

In [33]:
tensor3d = torch.ones(2,3,5)
tensor3d[0,1,:] += 1
tensor3d[0,2,:] += 2

tensor3d[1,1,:] += 2
tensor3d[1,2,:] += 1
print(tensor3d)

tensor2d = torch.ones(4,5) + torch.Tensor([1, 2, 3, 4, 5])
print(tensor2d)

tensorBias = torch.randn(4)
print(tensorBias)

# Multiplication with broadcasting working
print('Multiplication using @ operator:\n {}'.format(tensor3d @ tensor2d.t()))
print('Multiplication using matmul function:\n {}'.format(tensor3d.matmul(tensor2d.t())))

# Adding bias works
print((tensor3d @ tensor2d.t()) + tensorBias)

tensor([[[1., 1., 1., 1., 1.],
         [2., 2., 2., 2., 2.],
         [3., 3., 3., 3., 3.]],

        [[1., 1., 1., 1., 1.],
         [3., 3., 3., 3., 3.],
         [2., 2., 2., 2., 2.]]])
tensor([[2., 3., 4., 5., 6.],
        [2., 3., 4., 5., 6.],
        [2., 3., 4., 5., 6.],
        [2., 3., 4., 5., 6.]])
tensor([-0.7588,  1.0851,  1.2692, -1.4574])
Multiplication using @ operator:
 tensor([[[20., 20., 20., 20.],
         [40., 40., 40., 40.],
         [60., 60., 60., 60.]],

        [[20., 20., 20., 20.],
         [60., 60., 60., 60.],
         [40., 40., 40., 40.]]])
Multiplication using matmul function:
 tensor([[[20., 20., 20., 20.],
         [40., 40., 40., 40.],
         [60., 60., 60., 60.]],

        [[20., 20., 20., 20.],
         [60., 60., 60., 60.],
         [40., 40., 40., 40.]]])
tensor([[[19.2412, 21.0851, 21.2692, 18.5426],
         [39.2411, 41.0851, 41.2692, 38.5426],
         [59.2411, 61.0851, 61.2692, 58.5426]],

        [[19.2412, 21.0851, 21.2692, 18.5426],
 

## Dimensions of tensors

In [38]:
a = torch.ones(2 ,3, 5)
print(a, '\n Size: {}'.format(a.size()))

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]]) 
 Size: torch.Size([2, 3, 5])


## Aggregating only some instances from 3D tensor

In [60]:
tensor3d = torch.ones(2,3,6)
tensor3d[0,1,:] += 1
tensor3d[0,2,:] += 2

tensor3d[1,1,:] += 3
tensor3d[1,2,:] += 4

tensor3d[:,:,0] = 1
tensor3d[0,1:,0] = 0
tensor3d[1,0,0] = 0
tensor3d[1,2,0] = 1
# print(tensor3d)

valid_instances = tensor3d[:,:,0].type(torch.ByteTensor)
print('Valid instances:\n {}'.format(valid_instances))

NN_out = tensor3d[:,:,1:]
print('Output from NN:\n {}'.format(NN_out))

for i, indices in enumerate(valid_instances):
    print(NN_out[i,indices])

Valid instances:
 tensor([[1, 0, 0],
        [0, 1, 1]], dtype=torch.uint8)
Output from NN:
 tensor([[[1., 1., 1., 1., 1.],
         [2., 2., 2., 2., 2.],
         [3., 3., 3., 3., 3.]],

        [[1., 1., 1., 1., 1.],
         [4., 4., 4., 4., 4.],
         [5., 5., 5., 5., 5.]]])
tensor([[1., 1., 1., 1., 1.]])
tensor([[4., 4., 4., 4., 4.],
        [5., 5., 5., 5., 5.]])


## 4D tensor

In [8]:
tensor4d = torch.ones(2,2,3,5)
tensor4d[0,0,1,:] += 1
tensor4d[0,0,2,:] += 2

tensor4d[0,1,1,:] += 2
tensor4d[0,1,2,:] += 1


tensor4d[1,0,1,:] += 1
tensor4d[1,0,2,:] += 2

tensor4d[1,1,1,:] += 2
tensor4d[1,1,2,:] += 1
print(tensor4d)

tensor2d = torch.ones(4,5) + torch.Tensor([1, 2, 3, 4, 5])
print(tensor2d)

tensorBias = torch.randn(4)
print(tensorBias)

# Multiplication with broadcasting working
print('Multiplication using @ operator:\n {}'.format(tensor4d @ tensor2d.t()))
print('Multiplication using matmul function:\n {}'.format(tensor4d.matmul(tensor2d.t())))

# # Adding bias works
# print((tensor4d @ tensor2d.t()) + tensorBias)

tensor([[[[1., 1., 1., 1., 1.],
          [2., 2., 2., 2., 2.],
          [3., 3., 3., 3., 3.]],

         [[1., 1., 1., 1., 1.],
          [3., 3., 3., 3., 3.],
          [2., 2., 2., 2., 2.]]],


        [[[1., 1., 1., 1., 1.],
          [2., 2., 2., 2., 2.],
          [3., 3., 3., 3., 3.]],

         [[1., 1., 1., 1., 1.],
          [3., 3., 3., 3., 3.],
          [2., 2., 2., 2., 2.]]]])
tensor([[2., 3., 4., 5., 6.],
        [2., 3., 4., 5., 6.],
        [2., 3., 4., 5., 6.],
        [2., 3., 4., 5., 6.]])
tensor([-1.8746,  1.0237,  1.6971,  0.1340])
Multiplication using @ operator:
 tensor([[[[20., 20., 20., 20.],
          [40., 40., 40., 40.],
          [60., 60., 60., 60.]],

         [[20., 20., 20., 20.],
          [60., 60., 60., 60.],
          [40., 40., 40., 40.]]],


        [[[20., 20., 20., 20.],
          [40., 40., 40., 40.],
          [60., 60., 60., 60.]],

         [[20., 20., 20., 20.],
          [60., 60., 60., 60.],
          [40., 40., 40., 40.]]]])
Multiplica

## 1 in my_array

In [12]:
my_array = numpy.array([1., 0., 2., 4.])

In [14]:
print(1 in my_array)

True


## Indexing Numpy arrays and tensors

In [3]:
array = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print(array)
nparray = numpy.array(array)
print(nparray)
tensor = torch.tensor(array)
print(tensor)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[ 1  2  3  4  5  6  7  8  9 10]
tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


In [6]:
print(array[:2])
print(nparray[:2])
print(tensor[:6])

[1, 2]
[1 2]
tensor([1, 2, 3, 4, 5, 6])


## Summing empty array

In [18]:
tensor = torch.tensor([20, 50, 12])
print(tensor)

print(torch.sum(tensor[0:]))

print(sum(tensor[0:2]))

## Stratified sampling

In [15]:
from sklearn.model_selection import train_test_split
import numpy

y = [1, 1, -1, 1, -1, -1, 1, 1, 1, 1, -1, 1]
indices = numpy.arange(len(y))
print(indices)

i, i_t = train_test_split(indices, stratify = y)

# print(y, i)
# print(y_t, i_t)

print(i, i_t)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  8  1  9 11 10  7  4  5] [2 6 3]


## Normalization

In [36]:
import numpy

y = numpy.random.rand(10, 5)
print(y)

print(y.std(), y.mean())

y_normalized = (y - y.mean())/y.std()
print(y_normalized)

[[8.26848863e-01 2.60331974e-01 7.94174722e-01 7.59572733e-01
  5.32099193e-01]
 [3.75658501e-01 6.02018054e-01 3.21407786e-02 6.89338270e-01
  9.07379982e-01]
 [6.03652695e-01 7.01346854e-02 1.83233753e-01 3.14309932e-01
  9.58149073e-01]
 [2.79071887e-01 2.64151340e-02 9.42845742e-01 4.19210741e-01
  4.65723160e-04]
 [2.12099483e-01 6.26883938e-01 6.61220780e-01 2.21204144e-01
  7.85706598e-01]
 [8.90780711e-01 4.68219077e-01 9.10420186e-01 8.67048109e-01
  2.73698413e-01]
 [5.63709898e-01 8.81114082e-01 7.13846570e-01 8.47854549e-01
  4.55308050e-01]
 [3.90978009e-01 7.67985752e-01 9.22113234e-01 8.80473334e-01
  3.44759659e-01]
 [2.98716173e-01 8.16275006e-01 9.45835433e-01 9.50966724e-01
  2.94467320e-01]
 [4.35948912e-01 1.02992458e-01 6.44832474e-01 4.19319974e-01
  3.38096908e-01]]
0.29144006704001174 0.5501985679074951
[[ 0.94925278 -0.99460104  0.83714006  0.71841243 -0.06210325]
 [-0.59888837  0.17780495 -1.77757916  0.47742132  1.22557416]
 [ 0.18341379 -1.64721305 -1.25914

In [46]:
import torch
x = torch.Tensor([[1.5, 2.5, 3.5, 4.5, 5.5], [1, 2, 3, 4, 5], [1, 2, 3, 4, 5], [1, 2, 3, 4, 5]])

In [47]:
x.mean(dim = 0)

tensor([1.1250, 2.1250, 3.1250, 4.1250, 5.1250])

In [48]:
x.std(dim = 0)

tensor([0.2500, 0.2500, 0.2500, 0.2500, 0.2500])

In [49]:
std = x.std(dim = 0)
mean = x.mean(dim = 0)
print(std, mean)
print((x - mean)/std)

tensor([0.2500, 0.2500, 0.2500, 0.2500, 0.2500]) tensor([1.1250, 2.1250, 3.1250, 4.1250, 5.1250])
tensor([[ 1.5000,  1.5000,  1.5000,  1.5000,  1.5000],
        [-0.5000, -0.5000, -0.5000, -0.5000, -0.5000],
        [-0.5000, -0.5000, -0.5000, -0.5000, -0.5000],
        [-0.5000, -0.5000, -0.5000, -0.5000, -0.5000]])


## [for..]

In [50]:
[i for i in range(20)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

## n_instances of ns_instances

In [61]:
n_instances = [[1, 2, 3], [4], [5, 6, 7, 8, 9]]

In [63]:
print(n_instances)

[[1, 2, 3], [4], [5, 6, 7, 8, 9]]


In [66]:
n_instances[2][3]

8

In [67]:
import torch
n_instances = torch.Tensor([[1, 2, 3], [4], [5, 6, 7, 8, 9]])

ValueError: expected sequence of length 3 at dim 1 (got 1)

## Normalizing

In [1]:
import utils
import numpy
file_path = 'data1matlab/MIL-Data-2002-Musk-Corel-Trec9-MATLAB/fox_100x100_matlab.mat'
fox = utils.musk_dataset(file_path, normalize = False)

In [2]:
# print((fox.data == numpy.NaN))
print(fox.data.shape)

torch.Size([1320, 122])


## Checking parameters of linear layer

In [29]:
import torch

linear = torch.nn.Linear(10, 4, bias = True)

model = torch.nn.Sequential(
    linear,
    linear,
    linear,
    torch.nn.Linear(2,3, bias = True), 
    torch.nn.ReLU()
)

print(out_features in model[len(model)-1])

NameError: name 'out_features' is not defined

In [34]:
for 
try:
    print(model[len(model)-1].out_features)
except:
    pass

ValueError: Testing error!

## Input python array to torch, what is output?

In [12]:
import torch

class DummyModel(torch.nn.Module):
    def __init__(self):
        super().__init__()
    def forward(self,array):
        return array[:len(array)-1]

In [20]:
# 

[[2, 3], [1, 1, 2, 1]]
[[2, 3]]


## Forward with bagids

In [38]:
import numpy
import torch

inner_bagids = torch.Tensor([1, 1, 2, 3, 4, 4, 5, 6, 6])

bags, counts = numpy.unique(inner_bagids, return_counts=True)
print(bags, counts)


[1. 2. 3. 4. 5. 6.] [2 1 1 2 1 2]


In [65]:
mask = []
for i, n in enumerate(counts):
    mask.append(sum(counts[:i]))

print(mask)

[0, 2, 3, 4, 6, 7]


In [67]:
bagids = torch.Tensor([[1, 1,1,1,1,1,2,2,2],[1,1,1,2,2,2,3,4,4], [1, 1, 2, 3, 4, 4, 5, 6, 6]])
bagids = bagids[:len(bagids)-1]
print(bagids[:, mask])
print(mask)

tensor([[1., 1., 1., 1., 2., 2.],
        [1., 1., 2., 2., 3., 4.]])
[0, 2, 3, 4, 6, 7]


In [76]:
tensor = torch.Tensor([[1,2,3], [4, 5, 6]])
cropped_tensor = tensor[:len(bagids)-1]
cropped_tensor.shape[0] == 1

True

## Testing forwarding of bagids

In [9]:
from torch import nn
import torch
import BagModel

prepNN = torch.nn.Sequential(
    torch.nn.Linear(10, 5, bias = True),
    torch.nn.ReLU(),
)

afterNN = torch.nn.Sequential(
    torch.nn.Linear(5, 3, bias = True),
    torch.nn.ReLU(),
)

model = BagModel.BagModel(prepNN, afterNN, torch.mean).double()

In [15]:
data = torch.ones(12,10).double()
print(data)

bagids = torch.Tensor([[1,1,1,2,2,2,2,2,3,3,3,3]]).double()
print(bagids.shape)

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]], dtype=torch.float64)
torch.Size([1, 12])


In [16]:
model(data, bagids)

tensor([[0.1939, 0.0000, 0.0000],
        [0.1939, 0.0000, 0.0000],
        [0.1939, 0.0000, 0.0000]], dtype=torch.float64,
       grad_fn=<ReluBackward0>)

## Concating bagids

In [25]:
bagids = torch.Tensor([[1,1,1,1,1,1,2,2,2,3],\
                       [1,1,1,2,2,2,3,4,4,5],\
                       [1,1,2,3,4,4,5,6,6,7]])
print(bagids)

batch = []
batch.append(bagids[:,bagids[0] == 1])
batch.append(bagids[:,bagids[0] == 3])

print(batch)
bagids = torch.cat(batch, dim = 1)
print(bagids)

tensor([[1., 1., 1., 1., 1., 1., 2., 2., 2., 3.],
        [1., 1., 1., 2., 2., 2., 3., 4., 4., 5.],
        [1., 1., 2., 3., 4., 4., 5., 6., 6., 7.]])
[tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 2., 2., 2.],
        [1., 1., 2., 3., 4., 4.]]), tensor([[3.],
        [5.],
        [7.]])]
tensor([[1., 1., 1., 1., 1., 1., 3.],
        [1., 1., 1., 2., 2., 2., 5.],
        [1., 1., 2., 3., 4., 4., 7.]])


## Testing MilDataset

In [1]:
import mil

file_name = 'data/Musk1'

raw_data = open(file_name + '/data.csv')
raw_labels = open(file_name + '/labels.csv')
raw_bagids = open(file_name + '/bagids.csv')

data = numpy.loadtxt(raw_data, delimiter = '\t').transpose()
labels = numpy.loadtxt(raw_labels).transpose()
bagids = numpy.loadtxt(raw_bagids).transpose()

print(data)

FileNotFoundError: [Errno 2] No such file or directory: 'data/Musk1/data.csv'

## Absolute path

In [2]:
import os
os.path.abspath('mil.py')

'/Users/kuba/code/aic/mill_python/mil.py'

## Numpy functions in pytorch

In [136]:
import torch
import numpy
import time

In [137]:
inner_ids = torch.Tensor([3, 3, 1, 1, 1, 7, 7, 7, 7, 2, 2, 2])

In [141]:
start = time.time()
bags, idx, counts = numpy.unique(inner_bagids, return_counts = True, return_index = True)
bags = bags[numpy.argsort(idx)]
counts = counts[numpy.argsort(idx)]
print("Numpy vesrion | Elapsed time: {}".format(time.time()-start))

Numpy vesrion | Elapsed time: 0.0002779960632324219


In [142]:
print(bags, counts)

[3. 1. 7. 2.] [2 3 4 3]


In [143]:
# Final version?
start = time.time()
unique, inverse, counts = torch.unique(inner_ids, sorted = True, return_inverse = True, return_counts = True)
idx = torch.cat([(inverse == x).nonzero()[0] for x in range(len(unique))]).sort()[1]
bags = unique[idx]
counts = counts[idx]
print("Pytorch vesrion | Elapsed time: {}".format(time.time()-start))

Pytorch vesrion | Elapsed time: 0.0010409355163574219


In [144]:
print(bags,counts)

tensor([3., 1., 7., 2.]) tensor([2, 3, 4, 3])


## Creating empty tensors

In [233]:
import torch

In [248]:
a = torch.empty(0).long()
counts = torch.Tensor([1, 5, 1, 3])

In [249]:
a

tensor([], dtype=torch.int64)

In [250]:
append = torch.sum(counts, dtype = torch.int64).reshape(1)

In [251]:
torch.cat((a, append))

tensor([10])

## append vs cat

In [70]:
import torch
import timeit

In [72]:
ar = []
a = torch.Tensor([[1,2,3]])
b = torch.Tensor([[4,5,6]])
ar.append(a)
ar.append(b)
result = torch.cat(ar, dim = 0)

11.758095418997982

In [65]:
start = time.time()
ar = torch.empty((0,3))
a = torch.Tensor([[1,2,3]])
b = torch.Tensor([[4,5,6]])
ar = torch.cat((ar,a))
ar = torch.cat((ar,b))
print(time.time() - start)

0.0006508827209472656


## Random subset sampler

In [ ]:
torch.utils.data.SubsetRandomSampler

## CV

In [30]:
dataset_len = 100
n_folds = 7
indices = list(range(100))
print(indices)

fold_len = dataset_len/n_folds

for i in range(0, dataset_len, 7):
        
    

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]
0 7
7 14
14 21
21 28
28 35
35 42
42 49
49 56
56 63
63 70
70 77
77 84
84 91
91 98
98 105


In [25]:
import numpy
n_samples = 100
n_splits = 7
indices = numpy.arange(n_samples)
fold_sizes = numpy.full(n_splits, n_samples // n_splits, dtype=numpy.int)
fold_sizes[:n_samples % n_splits] += 1
current = 0
for fold_size in fold_sizes:
    start, stop = current, current + fold_size
    print(indices[start:stop])
    current = stop

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]
[30 31 32 33 34 35 36 37 38 39 40 41 42 43]
[44 45 46 47 48 49 50 51 52 53 54 55 56 57]
[58 59 60 61 62 63 64 65 66 67 68 69 70 71]
[72 73 74 75 76 77 78 79 80 81 82 83 84 85]
[86 87 88 89 90 91 92 93 94 95 96 97 98 99]


In [4]:
import torch

In [8]:
sampler = torch.utils.data.sampler.SubsetRandomSampler(indices = [1, 2, 3, 10, 11, 12])

In [9]:
for i in sampler:
    print(i)

12
10
2
3
11
1


In [23]:
errors = [1, 1]
numpy.mean(errors)

1.0

## Yaml

In [49]:
import yaml
import json

In [50]:
config = {}
config["n_neuron1"] = {}
config["n_neuron2"] = 7

In [51]:
config["n_neuron1"]["value"] = 5

In [52]:
yaml_file = yaml.dump(config)

In [53]:
data = yaml.load(yaml_file)

/usr/local/lib/python3.6/site-packages/ipykernel_launcher.py:1: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  """Entry point for launching an IPython kernel.


In [55]:
logp

{'value': 5}

In [56]:
n_neurons1 = 5
n_neurons2 = 5
n_neurons3 = 5
learning_rate = 1e-3
weight_decay = 1e-4

log = {}
log["config"] = {}
log["config"]["n_neurons1"] = n_neurons1
log["config"]["n_neurons2"] = n_neurons2
log["config"]["n_neurons3"] = n_neurons3
log["config"]["learning_rate"] = learning_rate
log["config"]["weight_decay"] = weight_decay

In [65]:
log["id"] = str(n_neurons1) + '_' + str(n_neurons2) + '_' + str(n_neurons3) + '_' + str(learning_rate) + '_' + str(weight_decay)

In [66]:
log

{'config': {'n_neurons1': 5,
  'n_neurons2': 5,
  'n_neurons3': 5,
  'learning_rate': 0.001,
  'weight_decay': 0.0001},
 'id': '5_5_5_0.001_0.0001'}

In [67]:
import uuid
filename = uuid.uuid4().hex

In [68]:
filename

'a9aa98a4246f4cef9c8fc882aca0eb66'

In [82]:
import numpy
numpy.logspace(-10, -2, num = 9)

array([1.e-10, 1.e-09, 1.e-08, 1.e-07, 1.e-06, 1.e-05, 1.e-04, 1.e-03,
       1.e-02])

In [78]:
1e-4

0.0001

In [83]:
import time

In [84]:
start = time.time()

In [85]:
time.time() - start

5.908906936645508

In [86]:
learning_rate_grid = numpy.logspace(-10, -2, num = 9)

In [92]:
learning_rate_grid[0].item()

1e-10

## Something with cuda

In [19]:
import torch
a = torch.Tensor([1, 2, 3], device = 'cpu')

In [3]:
a

tensor([1., 2., 3.])

In [10]:
a = torch.Tensor([1, 2, 3])
a = [a[0], a[1]]

In [11]:
a

[tensor(1.), tensor(2.)]

In [16]:
out_labels = torch.stack(a)

In [17]:
out_labels

tensor([1., 2.])

## Something

In [8]:
import torch
a = torch.rand((10,5))

In [6]:
a

tensor([[0.9229, 0.6855, 0.1926, 0.1540, 0.0628],
        [0.9702, 0.3062, 0.5516, 0.8029, 0.9007],
        [0.3397, 0.2631, 0.3896, 0.1163, 0.5305],
        [0.4334, 0.7186, 0.7373, 0.9346, 0.3472],
        [0.8808, 0.4511, 0.2017, 0.5354, 0.9571],
        [0.1218, 0.3974, 0.6952, 0.7764, 0.4998],
        [0.1323, 0.6156, 0.5997, 0.9026, 0.7783],
        [0.8522, 0.6426, 0.4540, 0.6932, 0.4264],
        [0.1089, 0.9828, 0.0400, 0.8898, 0.5481],
        [0.7794, 0.1174, 0.8688, 0.5546, 0.4540]])

## Creating 3D tensor

In [16]:
import torch
torch.Tensor(size = (2, 10, 5))
torch.rand(size = (2, 10, 5))

tensor([[[0.6038, 0.0401, 0.7619, 0.7717, 0.9917],
         [0.8872, 0.9818, 0.4465, 0.1990, 0.2825],
         [0.0847, 0.4469, 0.9764, 0.0146, 0.7255],
         [0.5856, 0.5349, 0.2665, 0.7717, 0.8157],
         [0.6690, 0.3662, 0.7468, 0.8674, 0.2418],
         [0.8077, 0.1848, 0.3721, 0.8526, 0.9489],
         [0.3117, 0.1853, 0.1479, 0.0173, 0.2029],
         [0.2422, 0.4695, 0.1235, 0.4527, 0.0233],
         [0.9036, 0.2864, 0.0556, 0.6664, 0.9121],
         [0.0732, 0.8263, 0.6277, 0.8738, 0.9644]],

        [[0.6512, 0.8371, 0.8293, 0.9288, 0.0777],
         [0.5730, 0.1617, 0.8290, 0.7082, 0.9335],
         [0.5364, 0.9597, 0.7232, 0.9584, 0.0550],
         [0.4708, 0.5701, 0.2550, 0.5137, 0.2055],
         [0.9599, 0.9944, 0.4400, 0.6541, 0.4997],
         [0.3091, 0.4877, 0.2079, 0.5830, 0.8993],
         [0.9606, 0.0190, 0.2750, 0.5533, 0.6643],
         [0.2944, 0.4312, 0.6376, 0.6281, 0.3907],
         [0.5791, 0.4887, 1.0000, 0.5949, 0.0783],
         [0.7962, 0.4200, 0.7

## Tensor with variable lenght elements

In [24]:
n_instances = torch.Tensor([[20, 3, 15], [21, 5, 14]])

In [25]:
print(n_instances)

tensor([[20.,  3., 15.],
        [21.,  5., 14.]])


## Testing init tensors

In [8]:
import torch
instances = torch.tensor([[1.0, 1.0, 1.0, 1.0],
                           [2.0, 2.0, 2.0, 2.0],
                           [3.0, 3.0, 3.0, 3.0],
                           [4.0, 4.0, 4.0, 4.0]], dtype = torch.double)

In [9]:
instances


tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.]], dtype=torch.float64)